export const LIST_ITEMS = [{
	"id": "1",
	"first_name": "Nikolas",
	"last_name": "Dono",
	"email": "ndono0@google.de",
	"skills": "Art",
	"experience": "21.6"
}, {
	"id": "2",
	"first_name": "Kira",
	"last_name": "Hinrich",
	"email": "khinrich1@ebay.com",
	"skills": "DPR",
	"experience": "5.5"
}, {
	"id": "3",
	"first_name": "Pernell",
	"last_name": "Hankey",
	"email": "phankey2@wunderground.com",
	"skills": "Boilers",
	"experience": "25.1"
}, {
	"id": "4",
	"first_name": "Herminia",
	"last_name": "Suthworth",
	"email": "hsuthworth3@columbia.edu",
	"skills": "Algorithms",
	"experience": "15.7"
}, {
	"id": "5",
	"first_name": "Dore",
	"last_name": "Tue",
	"email": "dtue4@ebay.com",
	"skills": "ASP.NET",
	"experience": "4.7"
}, {
	"id": "6",
	"first_name": "Berk",
	"last_name": "Tuohy",
	"email": "btuohy5@sbwire.com",
	"skills": "Supply Chain Management",
	"experience": "26.2"
}, {
	"id": "7",
	"first_name": "Grantham",
	"last_name": "Frondt",
	"email": "gfrondt6@dion.ne.jp",
	"skills": "Variable Frequency Drives",
	"experience": "11.9"
}, {
	"id": "8",
	"first_name": "Jackqueline",
	"last_name": "Saylor",
	"email": "jsaylor7@soundcloud.com",
	"skills": "Report Writing",
	"experience": "14.7"
}, {
	"id": "9",
	"first_name": "Felicia",
	"last_name": "Tillett",
	"email": "ftillett8@answers.com",
	"skills": "LSF",
	"experience": "19.0"
}, {
	"id": "10",
	"first_name": "Gisela",
	"last_name": "Sach",
	"email": "gsach9@blogs.com",
	"skills": "NATO",
	"experience": "4.0"
}, {
	"id": "11",
	"first_name": "Romonda",
	"last_name": "Richardes",
	"email": "rrichardesa@discuz.net",
	"skills": "DST",
	"experience": "29.8"
}, {
	"id": "12",
	"first_name": "Audrye",
	"last_name": "Bosward",
	"email": "aboswardb@go.com",
	"skills": "Rock Climbing",
	"experience": "15.1"
}, {
	"id": "13",
	"first_name": "Jerrylee",
	"last_name": "Anger",
	"email": "jangerc@go.com",
	"skills": "Local Government",
	"experience": "13.1"
}, {
	"id": "14",
	"first_name": "Zora",
	"last_name": "Dole",
	"email": "zdoled@google.fr",
	"skills": "CCSP",
	"experience": "11.8"
}, {
	"id": "15",
	"first_name": "Say",
	"last_name": "Hellwing",
	"email": "shellwinge@geocities.com",
	"skills": "Socket.io",
	"experience": "15.8"
}, {
	"id": "16",
	"first_name": "Nels",
	"last_name": "Wayt",
	"email": "nwaytf@nature.com",
	"skills": "SDI",
	"experience": "17.5"
}, {
	"id": "17",
	"first_name": "Eliza",
	"last_name": "Shackesby",
	"email": "eshackesbyg@sphinn.com",
	"skills": "JIT",
	"experience": "10.8"
}, {
	"id": "18",
	"first_name": "Dexter",
	"last_name": "Temby",
	"email": "dtembyh@unesco.org",
	"skills": "GSE",
	"experience": "12.2"
}, {
	"id": "19",
	"first_name": "Erika",
	"last_name": "Macewan",
	"email": "emacewani@deliciousdays.com",
	"skills": "FSC certified",
	"experience": "14.8"
}, {
	"id": "20",
	"first_name": "Rubetta",
	"last_name": "Orris",
	"email": "rorrisj@sina.com.cn",
	"skills": "Judicial Review",
	"experience": "16.2"
}, {
	"id": "21",
	"first_name": "Peter",
	"last_name": "Letford",
	"email": "pletfordk@live.com",
	"skills": "International Relations",
	"experience": "12.9"
}, {
	"id": "22",
	"first_name": "Harriet",
	"last_name": "O'Sheilds",
	"email": "hosheildsl@newsvine.com",
	"skills": "MCMS",
	"experience": "29.5"
}, {
	"id": "23",
	"first_name": "Bonnie",
	"last_name": "Leaf",
	"email": "bleafm@chron.com",
	"skills": "Gemba Kaizen",
	"experience": "6.8"
}, {
	"id": "24",
	"first_name": "Robinetta",
	"last_name": "Silverstone",
	"email": "rsilverstonen@netvibes.com",
	"skills": "Ksh",
	"experience": "4.8"
}, {
	"id": "25",
	"first_name": "Gabriello",
	"last_name": "Tidbald",
	"email": "gtidbaldo@ucoz.com",
	"skills": "Sensory Evaluation",
	"experience": "4.9"
}, {
	"id": "26",
	"first_name": "Tiebout",
	"last_name": "Myott",
	"email": "tmyottp@globo.com",
	"skills": "Pygame",
	"experience": "27.2"
}, {
	"id": "27",
	"first_name": "Carlie",
	"last_name": "Raymen",
	"email": "craymenq@goodreads.com",
	"skills": "CDO",
	"experience": "29.8"
}, {
	"id": "28",
	"first_name": "Clovis",
	"last_name": "Amoore",
	"email": "camoorer@theguardian.com",
	"skills": "GMRA",
	"experience": "23.8"
}, {
	"id": "29",
	"first_name": "Gerrie",
	"last_name": "Brydson",
	"email": "gbrydsons@vinaora.com",
	"skills": "McAfee Antivirus",
	"experience": "12.4"
}, {
	"id": "30",
	"first_name": "Henry",
	"last_name": "Proom",
	"email": "hproomt@time.com",
	"skills": "Musical Theatre",
	"experience": "26.9"
}, {
	"id": "31",
	"first_name": "Gabriell",
	"last_name": "Torvey",
	"email": "gtorveyu@springer.com",
	"skills": "LDOM",
	"experience": "24.0"
}, {
	"id": "32",
	"first_name": "Adolpho",
	"last_name": "Goulder",
	"email": "agoulderv@multiply.com",
	"skills": "SFX",
	"experience": "21.1"
}, {
	"id": "33",
	"first_name": "Ottilie",
	"last_name": "Nutkins",
	"email": "onutkinsw@ftc.gov",
	"skills": "DBVisualizer",
	"experience": "16.9"
}, {
	"id": "34",
	"first_name": "Harcourt",
	"last_name": "Levy",
	"email": "hlevyx@guardian.co.uk",
	"skills": "JCL",
	"experience": "11.1"
}, {
	"id": "35",
	"first_name": "Carlyn",
	"last_name": "Otton",
	"email": "cottony@discuz.net",
	"skills": "Community Organizing",
	"experience": "2.6"
}, {
	"id": "36",
	"first_name": "Burl",
	"last_name": "Learoid",
	"email": "blearoidz@census.gov",
	"skills": "Nutrition Education",
	"experience": "27.4"
}, {
	"id": "37",
	"first_name": "Twyla",
	"last_name": "McKinnell",
	"email": "tmckinnell10@github.com",
	"skills": "Hypertension",
	"experience": "12.0"
}, {
	"id": "38",
	"first_name": "Eva",
	"last_name": "Brocklebank",
	"email": "ebrocklebank11@dropbox.com",
	"skills": "Loan Servicing",
	"experience": "17.9"
}, {
	"id": "39",
	"first_name": "Windy",
	"last_name": "Wotton",
	"email": "wwotton12@ask.com",
	"skills": "PHP",
	"experience": "13.4"
}, {
	"id": "40",
	"first_name": "Coraline",
	"last_name": "Gee",
	"email": "cgee13@hatena.ne.jp",
	"skills": "On Location",
	"experience": "10.6"
}, {
	"id": "41",
	"first_name": "Odelinda",
	"last_name": "Beernt",
	"email": "obeernt14@sakura.ne.jp",
	"skills": "Umbilicals",
	"experience": "6.5"
}, {
	"id": "42",
	"first_name": "Michell",
	"last_name": "O'Curran",
	"email": "mocurran15@plala.or.jp",
	"skills": "Medical Writing",
	"experience": "12.5"
}, {
	"id": "43",
	"first_name": "Tootsie",
	"last_name": "Hoxey",
	"email": "thoxey16@lycos.com",
	"skills": "Style Guides",
	"experience": "8.0"
}, {
	"id": "44",
	"first_name": "Elbertine",
	"last_name": "Duetschens",
	"email": "eduetschens17@printfriendly.com",
	"skills": "Jeep",
	"experience": "21.8"
}, {
	"id": "45",
	"first_name": "Larissa",
	"last_name": "Berre",
	"email": "lberre18@craigslist.org",
	"skills": "Oz Principle",
	"experience": "16.7"
}, {
	"id": "46",
	"first_name": "Jamima",
	"last_name": "Scrivin",
	"email": "jscrivin19@google.co.jp",
	"skills": "CTM",
	"experience": "14.6"
}, {
	"id": "47",
	"first_name": "Karlens",
	"last_name": "Tapner",
	"email": "ktapner1a@bravesites.com",
	"skills": "Gold",
	"experience": "20.7"
}, {
	"id": "48",
	"first_name": "Olivette",
	"last_name": "Wakes",
	"email": "owakes1b@stumbleupon.com",
	"skills": "TMX",
	"experience": "1.5"
}, {
	"id": "49",
	"first_name": "Grissel",
	"last_name": "Kepe",
	"email": "gkepe1c@kickstarter.com",
	"skills": "EOU",
	"experience": "21.7"
}, {
	"id": "50",
	"first_name": "Collin",
	"last_name": "Rosendahl",
	"email": "tefdfsdfsd@jalbum.net",
	"skills": "Hospitality",
	"experience": "23.2"
}];

export const LIST_META = [{
    "key": "id",
    "label": "ID"
},
{
    "key": "first_name",
    "label": "First Name"
},
{
    "key": "last_name",
    "label": "Last Name"
},
{
    "key": "skills",
    "label": "Skills"
},
{
    "key": "experience",
    "label": "Experience"
}
];